### PR TITLE
Bytes20

### PR DESCRIPTION
**Pull request by rakita**
Needed to represent eth address that is 160bytes.

### CODE REVIEW

**Review by adlerjohn — COMMENTED** [review]
Hmmm. `fuel-types` should only represent types used by Fuel proper interdependent of base layer. Fuel doesn't have a notion of 20-byte things. If we're looking for something like types that can be used with an EVM base layer, then maybe a `fuel-types-evm` is in order?

**Comment by rakita** [comment]
That is why it is `Bytes20` as the naming is ambiguous it is not related to eth or something. Thing that i would like to avoid with this is to not use `H160` from `ethers` to specify configuration and use fuel primitive types, it seems nicer in that way, `fuel-types-vm` seems like overkill.

**Review by adlerjohn — APPROVED** [review]
I guess this is fine for now. If we start to get anything more though we should abstract out into other crates.

**Review by vlopes11 — COMMENTED** [review]
Consider adding the new type to the tests too. It might be a bit redundant since we already check the other variants, but its always better to play safe:

https://github.com/FuelLabs/fuel-types/blob/5daec7884ad405afe713e2087361c33c9713c4fc/tests/types.rs#L56

**Comment by rakita** [comment]
tests added

**Review by Voxelot — APPROVED** [review]

**Pull request merged**
